#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SwipeLayoutXamarin.Resource", IsApplication=false)]

namespace SwipeLayoutXamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public static int bring_to_clamp = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int clamp = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int gravity = 2130771968;
			
			// aapt resource value: 0x7f010006
			public static int left_swipe_enabled = 2130771974;
			
			// aapt resource value: 0x7f010007
			public static int right_swipe_enabled = 2130771975;
			
			// aapt resource value: 0x7f010001
			public static int sticky = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int sticky_sensitivity = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int swipe_enabled = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int center = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int left = 2130903041;
			
			// aapt resource value: 0x7f030006
			public static int no = 2130903046;
			
			// aapt resource value: 0x7f030003
			public static int none = 2130903043;
			
			// aapt resource value: 0x7f030005
			public static int parent = 2130903045;
			
			// aapt resource value: 0x7f030002
			public static int right = 2130903042;
			
			// aapt resource value: 0x7f030004
			public static int self = 2130903044;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020000
			public static int app_name = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SwipeLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 4
			public static int SwipeLayout_bring_to_clamp = 4;
			
			// aapt resource value: 3
			public static int SwipeLayout_clamp = 3;
			
			// aapt resource value: 0
			public static int SwipeLayout_gravity = 0;
			
			// aapt resource value: 6
			public static int SwipeLayout_left_swipe_enabled = 6;
			
			// aapt resource value: 7
			public static int SwipeLayout_right_swipe_enabled = 7;
			
			// aapt resource value: 1
			public static int SwipeLayout_sticky = 1;
			
			// aapt resource value: 2
			public static int SwipeLayout_sticky_sensitivity = 2;
			
			// aapt resource value: 5
			public static int SwipeLayout_swipe_enabled = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
